language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - git clone https://github.com/openplanets/jhove-old.git
  - cd jhove-old/jhove-releases
  - mvn clean install -DskipTests=true
  - cd ../..
  - git clone https://github.com/bl-dpt/dptutils.git
  - cd dptutils
  - mvn clean install -DskipTests=true
  - cd ..
