language: java
jdk:
# jhove-old fails to build with oraclejdk8
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - git clone https://github.com/bl-dpt/jhove.git
  - mvn clean install -DskipTests=true
  - cd ..
  - git clone https://github.com/bl-dpt/dptutils.git
  - cd dptutils
  - mvn clean install -DskipTests=true
  - cd ..
